config/routes.rb
ConnectedIn::Application.routes.draw do

root "profiles#show_all"

get "/profiles"                   => "profiles#show_all"

get "/profiles/:id" 							=> "profiles#show",	as: 'profile'
# get "/profiles/:username" 				=> "profiles#show",	as: 'profile'


get "/profiles/:first_name"				=> "profiles#show"




# get "profiles/will_leverett"       => "profiles#show_will",      as: 'will_profiles'
# get "profiles/harsh_patel"         => "profiles#show_harsh",     as: 'harsh_profiles'


# get "profiles/drew_montgomery"     => "profiles#show_drew",      as: 'drew_profiles'
# get "profiles/joe_marshall"        => "profiles#show_joe",       as: 'joe_profiles'



end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show_all
    @profile_all  = Profile.all
    @first_profie = Profile.first
    @last_profile = Profile.last.id
  end


  def show
    @profile = Profile.find(params[:id])
  end


end






  # def show
  #   profile_name = params[:profile_name]

  #   profile = {

  #     "harsh" => 
  #       {   :name               => "Harsh Patel",  
  #           :city               => "St. Louis",
  #           :description        => "The head of Maker Square",
  #           :picture_url        => "http://goo.gl/GwwMqe"
  #       },

  #     "drew" => 
  #       {   :name               => "Drew Montgomery",  
  #           :city               => "Somewhere",
  #           :description        => "he used to work a ton of hours",
  #           :picture_url        => "http://goo.gl/zckR91"
  #       },


  #     "joe" => 
  #       {   :name               => "Joe Marshall",  
  #           :city               => "Timbuktu",
  #           :description        => "the nice guy with curly red hair",
  #           :picture_url        => "http://goo.gl/NJpKgw"
  #       },


  #     "will" => 
  #       {   :name               => "Will Leverett",  
  #           :city               => "Kalamazoo",
  #           :description        => "The soccer fan",
  #           :picture_url        => "http://goo.gl/4gRZG9"
  #       }
  #   }

  #   @profiles = profile[profile_name]
  # end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectedIn</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/profiles/show.html.erb
<h1> ConnectedIn Profile </h1>


<h1>	    User Name: 			<%= @profile[:username] %>		</h1> 
<h2>			First Name: 		<%= @profile[:first_name] %>	</h2>
<h3>			Last Name: 			<%= @profile[:last_name] %>		</h3>
 <p>			Description: 		<%= @profile[:description] %>	</p>
<hr>
<h4>			Where I'm from: <img src = <%= @profile[:city_pic] %>> </h4>
<h4>			Profile Pic: 		<img src = <%= @profile[:profile_pic] %>> </h4>
	<p>			Facebook Page:  <%= @profile[:facebook_page] %></p>
<hr>

<p><%= link_to 'back', profiles_url %></p>

app/views/profiles/show_all.html.erb
<h1> All ConnectedIn Profiles </h1>

<ul>
	<% @profile_all.each do |profile| %>
	<li>username:		<%= link_to profile.username, profile_url(profile.id) %></li>
	<li>first name: <%= profile.first_name %></li>
	<hr>
	<% end %>
</ul>

app/views/profiles/show_drew.html.erb
<!-- Drew Montgomery -->


<h1><%=@student[:name]%>				</h1>
<h2><%=@student[:city]%>				</h2>
<h3><%=@student[:description]%>	</h3>

<img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-frc1/c28.28.357.357/s200x200/1240490_1398603777033311_1574409816_n.jpg"">

app/views/profiles/show_harsh.html.erb
<!-- Harsh Patel -->


<h1><%=@student[:name]%>				</h1>
<h2><%=@student[:city]%>				</h2>
<h3><%=@student[:description]%>	</h3>

<img src="http://goo.gl/GwwMqe">

app/views/profiles/show_joe.html.erb
<!-- Joe Marshall -->


<h1><%=@student[:name]%>				</h1>
<h2><%=@student[:city]%>				</h2>
<h3><%=@student[:description]%>	</h3>

<img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash4/1045186_10151572265288791_1936955603_n.jpg">

app/views/profiles/show_will.html.erb
<!-- Will Everett -->


<h1><%=@student[:name]%>				</h1>
<h2><%=@student[:city]%>				</h2>
<h3><%=@student[:description]%>	</h3>

<img src="https://scontent-b-dfw.xx.fbcdn.net/hphotos-frc3/1075290_10201606711633640_1377686348_n.jpg">